In [3]:
import requests
import pandas as pd

url1 = 'https://api.nobelprize.org/v1/laureate.json'
url = requests.get(url1).json()
df = pd.DataFrame(url['laureates'])
df

,id,firstname,surname,born,died,bornCountry,bornCountryCode,bornCity,diedCountry,diedCountryCode,diedCity,gender,prizes
0,1,Wilhelm Conrad,Röntgen,1845-03-27,1923-02-10,Prussia (now Germany),DE,Lennep (now Remscheid),Germany,DE,Munich,male,"[{'year': '1901', 'category': 'physics', 'shar..."
1,2,Hendrik A.,Lorentz,1853-07-18,1928-02-04,the Netherlands,NL,Arnhem,the Netherlands,NL,NaN,male,"[{'year': '1902', 'category': 'physics', 'shar..."
2,3,Pieter,Zeeman,1865-05-25,1943-10-09,the Netherlands,NL,Zonnemaire,the Netherlands,NL,Amsterdam,male,"[{'year': '1902', 'category': 'physics', 'shar..."
3,4,Henri,Becquerel,1852-12-15,1908-08-25,France,FR,Paris,France,FR,NaN,male,"[{'year': '1903', 'category': 'physics', 'shar..."
4,5,Pierre,Curie,1859-05-15,1906-04-19,France,FR,Paris,France,FR,Paris,male,"[{'year': '1903', 'category': 'physics', 'shar..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,1019,Memorial,NaN,1987-00-00,0000-00-00,NaN,NaN,NaN,NaN,NaN,NaN,org,"[{'year': '2022', 'category': 'peace', 'share'..."
977,1020,Center for Civil Liberties,NaN,2007-00-00,0000-00-00,NaN,NaN,NaN,NaN,NaN,NaN,org,"[{'year': '2022', 'category': 'peace', 'share'..."
978,1021,Ben,Bernanke,1953-12-13,0000-00-00,USA,US,"Augusta, GA",NaN,NaN,NaN,male,"[{'year': '2022', 'category': 'economics', 'sh..."
979,1022,Douglas,Diamond,1953-00-00,0000-00-00,NaN,NaN,NaN,NaN,NaN,NaN,male,"[{'year': '2022', 'category': 'economics', 'sh..."
980,1023,Philip,Dybvig,1955-05-22,0000-00-00,NaN,NaN,NaN,NaN,NaN,NaN,male,"[{'year': '2022', 'category': 'economics', 'sh..."

In [2]:
df1 = df[['id','firstname','surname','born','prizes','gender','bornCountryCode']]
df1['prizes'] = df['prizes'].apply(lambda x:x[0]['year'])
df1['category'] = df['prizes'].apply(lambda x:x[0]['category'])
df2 = df1.drop_duplicates(subset='prizes')
#df3 = df2.drop_duplicates(subset='category')
#df2.to_csv(r'C:\Users\sachikum\Documents\ML interview\segregate4.csv')
df2

C:\Users\sachikum\AppData\Local\Temp\ipykernel_11712\3570966640.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['prizes'] = df['prizes'].apply(lambda x:x[0]['year'])
C:\Users\sachikum\AppData\Local\Temp\ipykernel_11712\3570966640.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['category'] = df['prizes'].apply(lambda x:x[0]['category'])

,id,firstname,surname,born,prizes,gender,bornCountryCode,category
0,1,Wilhelm Conrad,Röntgen,1845-03-27,1901,male,DE,physics
1,2,Hendrik A.,Lorentz,1853-07-18,1902,male,NL,physics
3,4,Henri,Becquerel,1852-12-15,1903,male,FR,physics
6,8,Lord,Rayleigh,1842-11-12,1904,male,GB,physics
7,9,Philipp,Lenard,1862-06-07,1905,male,SK,physics
...,...,...,...,...,...,...,...,...
916,958,James P.,Allison,1948-08-07,2018,male,US,medicine
928,970,William,Kaelin,1957-11-23,2019,male,US,medicine
943,985,Harvey,Alter,1935-09-12,2020,male,US,medicine
955,997,David,Julius,1955-11-04,2021,male,US,medicine
968,1011,Svante,Pääbo,1955-04-20,2022,male,SE,medicine

In [3]:
df2.to_csv(r'C:\Users\sachikum\Documents\ML interview\segregate5.csv')

In [4]:
url3 = 'https://api.nobelprize.org/v1/country.json'
url4 = url = requests.get(url3).json()
df4 = pd.DataFrame(url4['countries'])
df4

                name code
0            Algeria   DZ
1          Argentina   AR
2          Australia   AU
3            Austria   AT
4    Austria-Hungary  NaN
..               ...  ...
131      Württemberg   DE
132            Yemen   YE
133       Yugoslavia   YU
134           Zambia   ZM
135         Zimbabwe   ZW

[136 rows x 2 columns]

In [4]:
lst = df.bornCountryCode.to_list()
lst

['DE',
 'NL',
 'NL',
 'FR',
 'FR',
 'PL',
 'GB',
 'SK',
 'GB',
 'PL',
 'LU',
 'IT',
 'DE',
 'NL',
 'RU',
 'SE',
 'NL',
 'DE',
 'GB',
 'AU',
 'GB',
 'DE',
 'DE',
 'CH',
 'DE',
 'DK',
 'US',
 'SE',
 'DE',
 'DE',
 'FR',
 'US',
 'GB',
 'GB',
 'FR',
 'IN',
 'DE',
 'AT',
 'GB',
 'GB',
 'AT',
 'US',
 'US',
 'GB',
 'IT',
 'US',
 'PL',
 'PL',
 'AT',
 'US',
 'GB',
 'GB',
 'JP',
 'GB',
 'GB',
 'IE',
 'CH',
 'US',
 'NL',
 'PL',
 'DE',
 'US',
 'DE',
 'GB',
 'US',
 'CN',
 'CN',
 'CN',
 'RU',
 'RU',
 'IT',
 'US',
 'US',
 'US',
 'DE',
 'AZ',
 'HU',
 'PL',
 'DE',
 'US',
 'RU',
 'AU',
 'JP',
 'US',
 'US',
 'FR',
 'FR',
 'US',
 'US',
 'SE',
 'FR',
 'HU',
 'US',
 'US',
 'JP',
 'NO',
 'GB',
 'GB',
 'GB',
 'DK',
 'US',
 'US',
 'US',
 'US',
 'US',
 'GB',
 'US',
 'RU',
 'DE',
 'US',
 'US',
 'PK',
 'US',
 'US',
 'US',
 'NL',
 'US',
 'SE',
 'US',
 'PK',
 'US',
 'IT',
 'NL',
 'PL',
 'DE',
 'DE',
 'CH',
 'DE',
 'CH',
 'US',
 'US',
 'DE',
 'US',
 'DE',
 'DE',
 'US',
 'US',
 'CA',
 'FR',
 'PL',
 'US',
 'US',
 'CA',
 'US',
 'US',
 'US',
 'US',
 'US',
 'US',
 'US',
 'DZ',
 'US',
 'US',
 'DE',
 'CN',
 'NL',
 'NL',
 'NL',
 'DE',
 'SE',
 'GB',
 'DE',
 'FR',
 'DE',
 'NZ',
 'LV',
 'RU',
 'FR',
 'FR',
 'FR',
 'US',
 'DE',
 'PL',
 'PL',
 'GB',
 'GB',
 'SI',
 'AT',
 'SE',
 'DE',
 'DE',
 'GB',
 'DE',
 'DE',
 'DE',
 'PL',
 'US',
 'US',
 'FR',
 'FR',
 'NL',
 'GB',
 'RU',
 'AT',
 'DE',
 'HR',
 'HU',
 'DE',
 'FI',
 'US',
 'US',
 'US',
 'GB',
 'SE',
 'CA',
 'DE',
 'PL',
 'US',
 'US',
 'GB',
 'GB',
 'DE',
 'US',
 'US',
 'GB',
 'RU',
 'GB',
 'GB',
 'CZ',
 'US',
 'US',
 'AT',
 'GB',
 'DE',
 'IT',
 'EG',
 'US',
 'US',
 'DE',
 'GB',
 'GB',
 'NO',
 'GB',
 'NO',
 'FR',
 'DE',
 'US',
 'US',
 'US',
 'DE',
 'GB',
 'US',
 'AU',
 'BA',
 'US',
 'RU',
 'GB',
 'GB',
 'DE',
 'US',
 'US',
 'JP',
 'UA',
 'LT',
 'CA',
 'US',
 'US',
 'US',
 'US',
 'TW',
 'DE',
 'US',
 'FR',
 'KR',
 'DE',
 'DE',
 'DE',
 'CA',
 'US',
 'US',
 'CH',
 'CA',
 'US',
 'GB',
 'HU',
 'NL',
 'MX',
 'US',
 'US',
 'GB',
 'US',
 'US',
 'GB',
 'DK',
 'AT',
 'GB',
 'EG',
 'PL',
 'IN',
 'DK',
 'RU',
 'DE',
 'IT',
 'ES',
 'FR',
 'UA',
 'PL',
 'CH',
 'DE',
 'SE',
 'FR',
 'FR',
 'AT',
 'BE',
 'DK',
 'GB',
 'DE',
 'CA',
 'GB',
 'ID',
 'DK',
 'AT',
 'FR',
 'NL',
 'GB',
 'AT',
 'DE',
 'GB',
 'GB',
 'US',
 'US',
 'US',
 'US',
 'DE',
 'GB',
 'DE',
 'HU',
 'BE',
 'PL',
 'DK',
 'US',
 'US',
 'US',
 'GB',
 'DE',
 'AU',
 'US',
 'CZ',
 'CZ',
 'AR',
 'CH',
 'CH',
 'PT',
 'US',
 'PL',
 'US',
 'ZA',
 'UA',
 'DE',
 'RU',
 'US',
 'US',
 'US',
 'SE',
 'FR',
 'DE',
 'US',
 'CH',
 'US',
 'US',
 'US',
 'ES',
 'US',
 'AU',
 'BR',
 'HU',
 'GB',
 'US',
 'NZ',
 'AU',
 'GB',
 'GB',
 'PL',
 'DE',
 'FR',
 'FR',
 'FR',
 'US',
 'CA',
 'FI',
 'US',
 'US',
 'US',
 'IN',
 'US',
 'DE',
 'US',
 'IT',
 'DE',
 'SE',
 'US',
 'US',
 'US',
 'GB',
 'AT',
 'AT',
 'NL',
 'BE',
 'GB',
 'RO',
 'US',
 'IT',
 'US',
 'US',
 'US',
 'FR',
 'LT',
 'US',
 'CH',
 'US',
 'US',
 'ZA',
 'GB',
 'VE',
 'FR',
 'US',
 'US',
 'CA',
 'SE',
 'SE',
 'SE',
 'GB',
 'US',
 'GB',
 'DE',
 'AR',
 'US',
 'US',
 'US',
 'IT',
 'JP',
 'GB',
 'US',
 'US',
 'US',
 'US',
 'US',
 'US',
 'DE',
 'DE',
 'CN',
 'US',
 'GB',
 'US',
 'US',
 'US',
 'US',
 'DE',
 'US',
 'AU',
 'CH',
 'US',
 'US',
 'US',
 'US',
 'PL',
 'CH',
 'FR',
 'CH',
 'CH',
 'GB',
 nan,
 'CZ',
 'US',
 'IT',
 'FR',
 'SE',
 'DK',
 'BE',
 'FR',
 nan,
 'NL',
 'AT',
 'US',
 'BE',
 nan,
 'US',
 'FR',
 'SE',
 'NO',
 'NO',
 'GB',
 'US',
 'FR',
 'DE',
 'FR',
 'DE',
 'US',
 'SE',
 'US',
 'US',
 'GB',
 'GB',
 'DE',
 'AR',
 'GB',
 nan,
 'US',
 'US',
 'US',
 nan,
 nan,
 'GB',
 'US',
 'FR',
 'FR',
 'US',
 nan,
 'CA',
 'BE',
 'GB',
 'ZW',
 'SE',
 nan,
 'US',
 nan,
 'FR',
 nan,
 'US',
 'DE',
 'DE',
 'VN',
 'FR',
 'JP',
 'RU',
 'GB',
 'GB',
 nan,
 'EG',
 'BY',
 'MK',
 'AR',
 'SE',
 'MX',
 'PL',
 'ZA',
 nan,
 'RO',
 'CR',
 nan,
 'CN',
 'RU',
 'MM',
 'GT',
 'ZA',
 'ZA',
 'EG',
 'BY',
 'IL',
 'PL',
 nan,
 'TL',
 'TL',
 nan,
 'US',
 'GB',
 'GB',
 nan,
 'FR',
 'DE',
 'NO',
 'FR',
 'ES',
 'PL',
 'IT',
 'IN',
 'DE',
 'SE',
 'DE',
 'BE',
 'PL',
 'IN',
 'FR',
 'SE',
 'DK',
 'DK',
 'CH',
 'NO',
 'FR',
 'ES',
 'IE',
 'PL',
 'IE',
 'IT',
 'FR',
 'DK',
 'DE',
 'US',
 'SE',
 'GB',
 'RU',
 'IT',
 'US',
 'FR',
 'US',
 'FI',
 'DK',
 'CL',
 'DE',
 'FR',
 'US',
 'US',
 'GB',
 'SE',
 'FR',
 'GB',
 'US',
 'IS',
 'ES',
 'DZ',
 'RU',
 'IT',
 'GP',
 'BA',
 'US',
 'TR',
 'FR',
 'RU',
 'UA',
 'DE',
 'GT',
 'JP',
 'IE',
 'RU',
 'CL',
 'DE',
 'GB',
 'SE',
 'SE',
 'IT',
 'CA',
 'ES',
 'PL',
 'GR',
 'LT',
 'BG',
 'CO',
 'GB',
 'CZ',
 'MG',
 'NG',
 'RU',
 'EG',
 'ES',
 'MX',
 'ZA',
 'LC',
 'US',
 'JP',
 'GB',
 'PL',
 'IT',
 'PT',
 'PL',
 'NO',
 'NL',
 'US',
 'BY',
 'GB',
 'US',
 'RU',
 'SE',
 'AT',
 'RU',
 'NL',
 'US',
 'SE',
 'GB',
 'US',
 'US',
 'LC',
 'US',
 'US',
 'US',
 'FR',
 'GB',
 'IT',
 'US',
 'US',
 'FR',
 'NO',
 'US',
 'US',
 'US',
 'GB',
 'US',
 'US',
 'US',
 'HU',
 'US',
 'PL',
 'US',
 'GB',
 'CA',
 'US',
 'CA',
 'IN',
 'CA',
 'RU',
 'SE',
 'US',
 'AT',
 'KR',
 'BY',
 'DE',
 'US',
 'US',
 'NZ',
 'JP',
 'US',
 'US',
 'CN',
 'US',
 'GB',
 'GB',
 'US',
 'DE',
 'US',
 'US',
 'JP',
 'US',
 'US',
 'US',
 'US',
 'TT',
 nan,
 'GH',
 'ZA',
 'US',
 'GB',
 'US',
 'JP',
 'IT',
 'US',
 'JP',
 'CH',
 'IL',
 'US',
 'HU',
 'US',
 'ZA',
 'US',
 'GB',
 'RU',
 'RU',
 'GB',
 'US',
 'US',
 'US',
 'GB',
 'IR',
 'US',
 'US',
 'US',
 'US',
 'US',
 'IL',
 'HU',
 'US',
 'AT',
 'KE',
 'NO',
 'US',
 'AU',
 'AU',
 'US',
 'US',
 'DE',
 'BE',
 'US',
 'US',
 nan,
 'EG',
 'DE',
 'US',
 'GB',
 'US',
 'US',
 'US',
 'US',
 'US',
 'US',
 'TR',
 'BD',
 nan,
 'IT',
 'GB',
 'GB',
 'FR',
 'CZ',
 'DE',
 'IR',
 nan,
 'US',
 'RU',
 'US',
 'US',
 'DE',
 'FR',
 'FR',
 'JP',
 'JP',
 'JP',
 'JP',
 'US',
 'US',
 'FR',
 'FI',
 'US',
 'AU',
 'US',
 'GB',
 'CN',
 'CA',
 'US',
 'IN',
 'US',
 'IL',
 'RO',
 'US',
 'US',
 'US',
 'GB',
 'RU',
 'RU',
 'US',
 'CN',
 'JP',
 'PE',
 'CN',
 'US',
 'US',
 'CY',
 'US',
 'LU',
 'CA',
 'US',
 'US',
 'US',
 'IL',
 'SE',
 'LR',
 'LR',
 'YE',
 'US',
 'US',
 'GB',
 'JP',
 'MA',
 'US',
 'US',
 'US',
 'CN',
 nan,
 'US',
 'US',
 'US',
 'US',
 'DE',
 'BE',
 'GB',
 'AT',
 'ZA',
 'IL',
 'CA',
 nan,
 'US',
 'US',
 'US',
 'US',
 'NO',
 'NO',
 'JP',
 'JP',
 'JP',
 'US',
 'RO',
 'US',
 'FR',
 'IN',
 'PK',
 'FR',
 'IE',
 'JP',
 'CN',
 'JP',
 'CA',
 'SE',
 'US',
 'TR',
 'UA',
 nan,
 'GB',
 'JP',
 'GB',
 'GB',
 'GB',
 'FR',
 'GB',
 'NL',
 'CO',
 'GB',
 'FI',
 'US',
 'US',
 'US',
 'US',
 'DE',
 'US',
 'US',
 'CH',
 'DE',
 'GB',
 'JP',
 nan,
 'US',
 'US',
 'JP',
 'US',
 'FR',
 'CA',
 'US',
 'US',
 'GB',
 'CD',
 'IQ',
 'US',
 'US',
 'US',
 'GB',
 'US',
 'CA',
 'CH',
 'CH',
 'DE',
 'GB',
 'JP',
 'PL',
 'AT',
 'ET',
 'IN',
 'FR',
 'US',
 'US',
 'GB',
 'US',
 'GB',
 'DE',
 'US',
 'FR',
 'US',
 'US',
 nan,
 'US',
 'US',
 'US',
 'LB',
 'JP',
 'DE',
 'IT',
 'DE',
 'GB',
 nan,
 'PH',
 'RU',
 'CA',
 'US',
 'NL',
 'SE',
 'FR',
 'US',
 'AT',
 'US',
 'DK',
 'FR',
 'RU',
 nan,
 nan,
 'US',
 nan,
 nan]

In [5]:
import pycountry
def get_country(n):
    country = pycountry.countries.get(alpha_3 = n)
    if country:
        return country.name
    else:
        return n
country_name = [get_country(name) for name in lst]
df["bornCountryCode"] = country_name
df.head()

LookupError:

In [17]:
pip install pycountry

Collecting pycountry
  Downloading pycountry-22.3.5.tar.gz (10.1 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Requirement already satisfied: setuptools in c:\users\sachikum\anaconda3\lib\site-packages (from pycountry) (61.2.0)
Building wheels for collected packages: pycountry
  Building wheel for pycountry (PEP 517): started
  Building wheel for pycountry (PEP 517): finished with status 'done'
  Created wheel for pycountry: filename=pycountry-22.3.5-py2.py3-none-any.whl size=10681895 sha256=a8319f59ee149b2a436c7b8cf7b22f920ad6596043dca7e0bc7a9f6dad4f90be
  Stored in directory: c:\users\sachikum\appdata\local\pip\cache\wheels\47\15\92\e6dc85fcb0686c82e1edbcfdf80cfe4808c058813fed0baa8f
Successfully built pycountry
Installing collected packages: pycountry
Successfully installed pycountry-22.3.5
Note: you may need to restart the kernel to use updated packages.